\documentclass[12pt]{article}
\usepackage{amsmath, amsfonts, amssymb} %These packages allow for various math types to be used.  
\usepackage{graphicx,subfig} %this allows for the use of figures and subfigures
\usepackage{float}
\usepackage[english]{babel}
\usepackage{caption}
\usepackage{accents} 
\usepackage{color}
\usepackage{amsthm} %This creates theorem environments.  You still have to specific what a theorem is (which we'll see later).
\usepackage[margin=1in]{geometry}
\graphicspath{ {imagesUsingMultiCure/} }
\usepackage{natbib}
\usepackage{courier}
\usepackage{listings}
\usepackage{tikz}

\lstset{basicstyle=\footnotesize\ttfamily,breaklines=true}

\title{Example MultiCure Code}
\author{\textbf{Lauren J Beesley} \\
\small Department of Biostatistics, University of Michigan\\
\small Contact: lbeesley@umich.edu}
\date{\today}   
 
%\VignetteIndexEntry{Example}
%\VignetteEngine{knitr}
\begin{document}
%\SweaveOpts{concordance=TRUE}
\maketitle 
%These two lines are to avoid having lots of white space before and after align statements
\abovedisplayskip=0pt
\belowdisplayskip=0pt
\raggedbottom


In this vignette, we provide code for fitting multistate cure models using the package \textit{MultiCure} for an example dataset. 
%%%
\section*{Load in Code}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
library(devtools)
install_github("lbeesleyBIOSTAT/MultiCure")
library(MultiCure)
\end{lstlisting}


%%%
\section*{View Vignettes}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
browseVignettes('MultiCure')
\end{lstlisting}

%%%
\section*{Simulate Data}
The following code simulates datasets under a multistate cure model with 1) no covariate missingness or unequal censoring, 2) covariate missingness, and 3) unequal censoring
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
NONE = SimulateMultiCure(type = 'NoMissingness') 
COV = SimulateMultiCure(type = 'CovariateMissingness')
CENS = SimulateMultiCure(type = 'UnequalCensoring')
\end{lstlisting}

%%%
\section*{Visualize Data}
The following is a RShiny function for visualizing the observed information for recurrence and death. We note that there is not unequal censoring in this simulated dataset.Note: We have a very small probability of experiencing a recurrence after about time 50 (although they may rarely happen), so it seems generally reasonable to assume subjects still at risk for recurrence and death after time 50 are cured.\\
\\
\noindent \textbf{Data with no unequal censoring:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
datWIDE = data.frame( Y_R = NONE$Y_R, Y_D = NONE$Y_D, delta_R = NONE$delta_R, delta_D = NONE$delta_D)
VISUALIZEDATA(datWIDE)
\end{lstlisting}
\noindent \textbf{Data with unequal censoring:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
datWIDE = data.frame( Y_R = CENS$Y_R, Y_D = CENS$Y_D, delta_R = CENS$delta_R, delta_D = CENS$delta_D)
VISUALIZEDATA(datWIDE)
\end{lstlisting}






\newpage
%%%
\section*{Fitting to Complete Data with Weibull Baselines}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
Cov = data.frame(NONE$X1,NONE$X2)
VARS = names(Cov)
TransCov = list(Trans13 = VARS, Trans24 = VARS, Trans14 = VARS, Trans34 = VARS, PNonCure = VARS)
datWIDE = data.frame( Y_R = NONE$Y_R, Y_D = NONE$Y_D, delta_R = NONE$delta_R , delta_D = NONE$delta_D, G = NONE$G)
\end{lstlisting}
\noindent \textbf{Parameter Estimation:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
fit = MultiCure(iternum = 50, datWIDE  = datWIDE, Cov = Cov, trace = T, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'weib')
beta = fit[[1]]
alpha = fit[[2]]
scale = fit[[3]]
shape = fit[[4]]
beta_save = fit[[5]]
alpha_save = fit[[6]]
scale_save = fit[[7]]
shape_save = fit[[8]]
\end{lstlisting}
\noindent \textbf{Variance Estimation:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
OUT = VarianceEM(fit,iternum=20, bootnum=50, datWIDE, Cov, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'weib')
\end{lstlisting}



\newpage
%%%
\section*{Fitting to Data with Covariate Missingness with Weibull Baselines}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
Cov = data.frame(X1 = COV$X1, X2 = COV$X2)
VARS = names(Cov)
TransCov = list(Trans13 = VARS, Trans24 = VARS, Trans14 = VARS, Trans34 = VARS, PNonCure = VARS)
datWIDE = data.frame( Y_R = COV$Y_R, Y_D = COV$Y_D, delta_R = COV$delta_R , delta_D = COV$delta_D, G = COV$G)
\end{lstlisting}
\noindent \textbf{Parameter Estimation:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
ITERNUM = 200
fit = MultiCure(iternum = ITERNUM, datWIDE  = datWIDE, Cov = Cov, COVIMPUTEFUNCTION  = COVIMPUTEFUNCTION, COVIMPUTEINITIALIZE = COVIMPUTEINITIALIZE, IMPNUM = 10, trace = T, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'weib')
beta_save = fit[[5]]
alpha_save = fit[[6]]
scale_save = fit[[7]]
shape_save = fit[[8]]
### Theta-Hat can be estimated as the mean of the last few iterations
beta = apply(beta_save[,(ITERNUM-10): ITERNUM], 1, mean)
alpha =  apply(alpha_save[,(ITERNUM-10): ITERNUM], 1, mean)
scale =  apply(scale_save[,(ITERNUM-10): ITERNUM], 1, mean)
shape =  apply(shape_save[,(ITERNUM-10): ITERNUM], 1, mean)
\end{lstlisting}
\noindent \textbf{Proper Imputations:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
Proper = ProperDraws_MC(datWIDE,Cov, CovImp = fit[[9]], GImp = fit[[10]], YRImp = fit[[11]], deltaRImp = fit[[12]], COVIMPUTEFUNCTION = COVIMPUTEFUNCTION,  COVIMPUTEINITIALIZE = COVIMPUTEINITIALIZE, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'weib')
CovImp = Proper[[1]]
GImp = Proper[[2]]
YRImp = Proper[[3]]
deltaRImp = Proper[[4]]	
\end{lstlisting}
\noindent \textbf{Variance Estimation Method 1:} This code performs variance estimation by fitting a multistate cure model to each one of the imputed datasets. For each imputed dataset, we use the standard software estimated SEs from the Logistic regression and proportional hazards model fits. Then, Rubin's rules are applied to obtain the final variance estimator across imputed datasets. This function also provides a different estimate of Theta based on Rubin's rules (based only on the final iteration). We have found the estimate from the mean of the last few iterations (above) may have slightly better coverage unless the number of imputations is large.
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
OUT = VarianceMCEM_NOBOOT(fit,datWIDE,  CovImp, GImp, YRImp, deltaRImp, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'weib')		
\end{lstlisting}
\noindent \textbf{Variance Estimation Method 2:} This code performs variance estimation by fitting a multistate cure model to each one of the imputed datasets. For each imputed dataset, variances are estimated by fitting the multistate cure model to many bootstrap samples the imputed data. Then Rubin's rules are applied to obtain the final variance estimator across imputed datasets. This function also provides a different estimate of Theta based on Rubin's rules.
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
OUT = VarianceMCEM_BOOT(fit,bootnum = 50, datWIDE = datWIDE,  CovImp, GImp, YRImp, deltaRImp, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'weib')		
\end{lstlisting}





\newpage
%%%
\section*{Fitting to Data with Unequal Censoring with Weibull Baselines}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
Cov = data.frame(X1 = CENS$X1, X2 = CENS$X2)
VARS = names(Cov)
TransCov = list(Trans13 = VARS, Trans24 = VARS, Trans14 = VARS, Trans34 = VARS, PNonCure = VARS)
datWIDE = data.frame( Y_R = CENS$Y_R, Y_D = CENS$Y_D, delta_R = CENS$delta_R, delta_D = CENS$delta_D, G = CENS$G)
\end{lstlisting}
\noindent \textbf{Parameter Estimation:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
ITERNUM = 200
fit = MultiCure(iternum = ITERNUM, datWIDE  = datWIDE, Cov = Cov, IMPNUM = 10,trace = T, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'weib', UNEQUALCENSIMPUTE = UNEQUALCENSIMPUTEWEIBREJECTION)
beta_save = fit[[5]]
alpha_save = fit[[6]]
scale_save = fit[[7]]
shape_save = fit[[8]]
### Theta-Hat can be estimating as the mean of the last few iterations
beta = apply(beta_save[,(ITERNUM-10): ITERNUM], 1, mean)
alpha =  apply(alpha_save[,(ITERNUM-10): ITERNUM], 1, mean)
scale =  apply(scale_save[,(ITERNUM-10): ITERNUM], 1, mean)
shape =  apply(shape_save[,(ITERNUM-10): ITERNUM], 1, mean)
\end{lstlisting}
\noindent \textbf{Proper Imputations:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
Proper = ProperDraws_MC(datWIDE,Cov, CovImp = fit[[9]], GImp = fit[[10]], YRImp = fit[[11]], deltaRImp = fit[[12]], ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'weib', UNEQUALCENSIMPUTE = UNEQUALCENSIMPUTEWEIB)
CovImp = Proper[[1]]
GImp = Proper[[2]]
YRImp = Proper[[3]]
deltaRImp = Proper[[4]]	
\end{lstlisting}
\noindent \textbf{Variance Estimation Method 1:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
OUT = VarianceMCEM_NOBOOT(fit,datWIDE,  CovImp, GImp, YRImp, deltaRImp, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'weib')		
\end{lstlisting}




\newpage
%%%
\section*{Fitting to Complete Data with Cox Baselines}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
Cov = data.frame(NONE$X1,NONE$X2)
VARS = names(Cov)
TransCov = list(Trans13 = VARS, Trans24 = VARS, Trans14 = VARS, Trans34 = VARS, PNonCure = VARS)
datWIDE = data.frame( Y_R = NONE$Y_R, Y_D = NONE$Y_D, delta_R = NONE$delta_R , delta_D = NONE$delta_D, G = NONE$G)
\end{lstlisting}
\noindent \textbf{Parameter Estimation:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
fit = MultiCure(iternum = 50, datWIDE  = datWIDE, Cov = Cov, trace = T, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'cox')
beta = fit[[1]]
alpha = fit[[2]]
beta_save = fit[[3]]
alpha_save = fit[[4]]
\end{lstlisting}
\noindent \textbf{Variance Estimation:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
OUT = VarianceEM(fit,iternum=20, bootnum=50, datWIDE, Cov, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'cox')
\end{lstlisting}



\newpage
%%%
\section*{Fitting to Data with Covariate Missingness with Cox Baselines}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
Cov = data.frame(X1 = COV$X1, X2 = COV$X2)
VARS = names(Cov)
TransCov = list(Trans13 = VARS, Trans24 = VARS, Trans14 = VARS, Trans34 = VARS, PNonCure = VARS)
datWIDE = data.frame( Y_R = COV$Y_R, Y_D = COV$Y_D, delta_R = COV$delta_R , delta_D = COV$delta_D, G = COV$G)
\end{lstlisting}
\noindent \textbf{Parameter Estimation:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
ITERNUM = 200
fit = MultiCure(iternum = ITERNUM, datWIDE  = datWIDE, Cov = Cov, COVIMPUTEFUNCTION  = COVIMPUTEFUNCTION, COVIMPUTEINITIALIZE = COVIMPUTEINITIALIZE, IMPNUM = 10,trace = T, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'cox')
beta_save = fit[[3]]
alpha_save = fit[[4]]
### Theta-Hat can be estimated as the mean of the last few iterations
beta = apply(beta_save[,(ITERNUM-10): ITERNUM], 1, mean)
alpha =  apply(alpha_save[,(ITERNUM-10): ITERNUM], 1, mean)
\end{lstlisting}
\noindent \textbf{Proper Imputations:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
Proper = ProperDraws_MC(datWIDE,Cov, CovImp = fit[[9]], GImp = fit[[10]], YRImp = fit[[11]], deltaRImp = fit[[12]], COVIMPUTEFUNCTION = COVIMPUTEFUNCTION,  COVIMPUTEINITIALIZE = COVIMPUTEINITIALIZE, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'cox')
CovImp = Proper[[1]]
GImp = Proper[[2]]
YRImp = Proper[[3]]
deltaRImp = Proper[[4]]	
\end{lstlisting}
\noindent \textbf{Variance Estimation Method 1:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
OUT = VarianceMCEM_NOBOOT(fit,datWIDE,  CovImp, GImp, YRImp, deltaRImp, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'cox')		
\end{lstlisting}
\noindent \textbf{Variance Estimation Method 2:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
OUT = VarianceMCEM_BOOT(fit,bootnum = 50, datWIDE = datWIDE,  CovImp, GImp, YRImp, deltaRImp, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'cox')		
\end{lstlisting}



\newpage
%%%
\section*{Fitting to Data with Unequal Censoring with Cox Baselines}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
Cov = data.frame(X1 = CENS$X1, X2 = CENS$X2)
VARS = names(Cov)
TransCov = list(Trans13 = VARS, Trans24 = VARS, Trans14 = VARS, Trans34 = VARS, PNonCure = VARS)
datWIDE = data.frame( Y_R = CENS$Y_R, Y_D = CENS$Y_D, delta_R = CENS$delta_R, delta_D = CENS$delta_D, G = CENS$G)
\end{lstlisting}
\noindent \textbf{Parameter Estimation:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
ITERNUM = 200
fit = MultiCure(iternum = ITERNUM, datWIDE  = datWIDE, Cov = Cov, IMPNUM = 10,trace = T, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'cox', UNEQUALCENSIMPUTE = UNEQUALCENSIMPUTEWEIBREJECTION)
beta_save = fit[[3]]
alpha_save = fit[[4]]
### Theta-Hat can be estimating as the mean of the last few iterations
beta = apply(beta_save[,(ITERNUM-10): ITERNUM], 1, mean)
alpha =  apply(alpha_save[,(ITERNUM-10): ITERNUM], 1, mean)
\end{lstlisting}
\noindent \textbf{Proper Imputations:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
Proper = ProperDraws_MC(datWIDE,Cov, CovImp = fit[[9]], GImp = fit[[10]], YRImp = fit[[11]], deltaRImp = fit[[12]], ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'cox', UNEQUALCENSIMPUTE = UNEQUALCENSIMPUTEWEIB)
CovImp = Proper[[1]]
GImp = Proper[[2]]
YRImp = Proper[[3]]
deltaRImp = Proper[[4]]	
\end{lstlisting}
\noindent \textbf{Variance Estimation Method 1:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
OUT = VarianceMCEM_NOBOOT(fit,datWIDE,  CovImp, GImp, YRImp, deltaRImp, ASSUME = 'SameHazard', TransCov = TransCov, BASELINE = 'cox')		
\end{lstlisting}




\newpage
%%%
\section*{Examine Convergence of the Parameter Values}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

par(mfrow=c(1,3))

matplot(t(beta_save[c(1,3,5,7),]), type = 'l',lty = 1, lwd = 2, col =  cbPalette[c(6,7,4,8)], main = 'Beta Parameters for X1', xlab = 'Iterations', ylab = 'Estimated Value')
legend(x='topright', fill = cbPalette[c(6,7,4,8)], legend = c( 'Transition 1->3', 'Transition 2->4', 'Transition 1->4', 'Transition 3->4'), cex = 0.8)

matplot(t(beta_save[c(2,4,6,8),]), type = 'l',lty = 1, lwd = 2, col =  cbPalette[c(6,7,4,8)], main = 'Beta Parameters for X2', xlab = 'Iterations', ylab = 'Estimated Value')
legend(x='bottomright', fill = cbPalette[c(6,7,4,8)], legend = c( 'Transition 1->3', 'Transition 2->4', 'Transition 1->4', 'Transition 3->4'), cex = 0.8)

matplot(t(alpha_save), type = 'l',lty = 1, lwd = 2, col =  cbPalette[c(6,7,4)], main = 'Alpha Parameters', xlab = 'Iterations', ylab = 'Estimated Value')
legend(x='topright', fill = cbPalette[c(6,7,4,8)], legend = c( 'Intercept', 'X1', 'X2'), cex = 0.8)
\end{lstlisting}


\newpage
%%%
\section*{Estimate State Occupancy Probabilities}

\noindent \textbf{Weibull Baseline Hazards:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
STATEOCCUPANCYWEIB(times = seq(0,max(datWIDE$Y_D),1), TransCov, newCov = data.frame(X1 = c(0,0.5), X2 = c(0,0.5)), beta, alpha, scale, shape) 
\end{lstlisting}
\noindent \textbf{Cox Baseline Hazards, EM Algorithm:}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
Haz = BaselineHazard_NOIMP(datWIDE, Cov, beta, alpha, TransCov, ASSUME = 'SameHazard', p=p_save[,50])	
STATEOCCUPANCYCOX_NOIMP(times = seq(0,max(datWIDE$Y_D),1), TransCov, newCov = data.frame(X1 = c(0,0.5), X2 = c(0,0.5)), beta, alpha, Haz_13 = Haz[[1]], Haz_24 = Haz[[2]], Haz_14 = Haz[[3]], Haz_34 = Haz[[4]]) 
\end{lstlisting}
\noindent \textbf{Cox Baseline Hazards, MCEM Algorithm: (Be Patient, the integrations are tricky)}
\begin{lstlisting}[language=R, showstringspaces=false, keywords={}]
haz = Baselinehazard_IMP(datWIDE, CovImp,GImp, YRImp,deltaRImp, beta, alpha, TransCov, ASSUME = 'SameHazard')	
STATEOCCUPANCYCOX_IMP(times = seq(0,max(datWIDE$Y_D),5), TransCov, newCov = data.frame(X1 = c(0), X2 = c(0)), beta, alpha, Basehaz13 = haz[[1]], Basehaz24 = haz[[2]], Basehaz14 = haz[[3]], Basehaz34 = haz[[4]]) 
\end{lstlisting}




\end{document}